from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from dbscan import dbscan
from sklearn import datasets


def plot_raw_dataset(x: np.ndarray, output_path: Path) -> None:
    """
    Plot and save the raw two-moon dataset.

    Parameters
    ----------
    x : np.ndarray
        Input data with shape (n_samples, 2).
    output_path : Path
        Path used to save the generated figure.
    """
    plt.figure(figsize=(6, 5))
    plt.scatter(x[:, 0], x[:, 1], s=20)
    plt.xlabel("feature1")
    plt.ylabel("feature2")
    plt.grid(True)
    plt.title("Dataset generated by make_moons")
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)


def plot_cluster_result(x: np.ndarray, labels: np.ndarray, output_path: Path) -> None:
    """
    Plot and save the DBSCAN clustering result.

    Parameters
    ----------
    x : np.ndarray
        Input data with shape (n_samples, 2).
    labels : np.ndarray
        Cluster labels returned by DBSCAN.
    output_path : Path
        Path used to save the generated figure.
    """
    scatter_colors = [
        "blue",
        "green",
        "yellow",
        "red",
        "purple",
        "orange",
        "brown",
    ]

    plt.figure(figsize=(6, 5))
    for label in np.unique(labels):
        cluster_points = x[labels == label]

        if label == -1:
            plt.scatter(cluster_points[:, 0], cluster_points[:, 1], color="black", s=20)
            continue

        color = scatter_colors[label % len(scatter_colors)]
        plt.scatter(cluster_points[:, 0], cluster_points[:, 1], color=color, s=20)

    plt.xlabel("feature1")
    plt.ylabel("feature2")
    plt.grid(True)
    plt.title("DBSCAN clustering result")
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)


if __name__ == "__main__":
    assets_dir = Path(__file__).resolve().parent / "assets"
    assets_dir.mkdir(exist_ok=True)

    x, _ = datasets.make_moons(n_samples=500, noise=0.1, random_state=1)
    labels = dbscan(x, eps=0.2, min_pts=20)

    plot_raw_dataset(x, assets_dir / "dbscan_raw_dataset.png")
    plot_cluster_result(x, labels, assets_dir / "dbscan_result.png")

    if matplotlib.get_backend().lower() != "agg":
        plt.show()
